version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "07:00"
      timezone: "Asia/Shanghai"
  - package-ecosystem: "cargo"
    directories:
      - "/dingtalk-sdk"
      - "/dingtalk-cli"
    schedule:
      interval: "daily"
      time: "07:00"
      timezone: "Asia/Shanghai"
    open-pull-requests-limit: 20
